import argparse
import csv
import json
from pathlib import Path


def build_rules(input_path: Path, output_path: Path) -> None:
    rules = []
    with input_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for index, row in enumerate(reader, start=1):
            value = (row.get("value") or "").strip()
            if not value:
                continue

            rules.append(
                {
                    "id": (row.get("id") or f"custom_{index:05d}").strip(),
                    "type": (row.get("type") or "word").strip(),
                    "value": value,
                    "category": (row.get("category") or "custom").strip(),
                    "severity": int(row.get("severity") or 1),
                    "enabled": (row.get("enabled") or "true").strip().lower() != "false",
                    "description": (row.get("description") or "").strip(),
                }
            )

    payload = {
        "version": "1.0.0",
        "language": "ko",
        "description": "Generated by tools/build_rules_from_csv.py",
        "rules": rules,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="CSV file path")
    parser.add_argument("--output", default="data/forbidden_words.ko.json", help="Output JSON path")
    args = parser.parse_args()

    build_rules(Path(args.input), Path(args.output))


if __name__ == "__main__":
    main()
